"""Phase 4 — actuation: behaviour cloning, then preference optimization.

Cloning teaches the action distribution. It cannot teach *preference* between
two action sequences that both parse, because the cloning loss only ever sees
the good one. Direct Preference Optimization supplies the second half, using
pairs whose winner and loser are decided by the environment's goal predicate
rather than by a rater:

    L_DPO = -log sigma( beta * [ (logp_w - logp_w_ref) - (logp_l - logp_l_ref) ] )

Losers are generated by *perturbing a winner* in ways that are individually
plausible and jointly wrong — the right opcode at the wrong coordinates, the
right coordinates in the wrong order, an extra object. Sampling losers from the
untrained policy instead would make the pair trivially separable and teach
nothing beyond what cloning already did.
"""

from __future__ import annotations

import argparse
import copy
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np
import torch
import torch.nn.functional as F

from ..agency.actions import Action, Op, actions_to_span_payload
from ..agency.scene import Goal, SceneEditor
from ..codecs.bank import TensorBatch
from ..runtime.device import device_of, continuous_dims
from ..codecs.spans import MODALITY_INDEX, Sample, Span, collate
from .tasks import Item, control_span
from .trainer import load_checkpoint


def corrupt(actions: Sequence[Action], rng: np.random.Generator) -> list[Action]:
    """A plausible but wrong trajectory. Never a random one."""
    out = [Action(a.op, a.operands, a.text) for a in actions]
    if not out:
        return out
    mode = int(rng.integers(0, 4 if len(out) > 1 else 3))
    i = int(rng.integers(len(out)))
    if mode == 0:                                    # right op, wrong place
        ops = list(out[i].operands)
        axis = int(rng.integers(0, min(3, len(ops))))
        ops[axis] = float(ops[axis] + rng.choice([-1.0, 1.0]) * rng.uniform(0.5, 2.0))
        out[i] = Action(out[i].op, tuple(ops), out[i].text)
    elif mode == 1:                                  # wrong primitive
        alt = {Op.ADD_CUBE: Op.ADD_SPHERE, Op.ADD_SPHERE: Op.ADD_PLANE,
               Op.ADD_PLANE: Op.ADD_CUBE}.get(out[i].op, Op.ADD_CUBE)
        out[i] = Action(alt, out[i].operands, out[i].text)
    elif mode == 2:                                  # one object too many
        out.append(Action(out[i].op, out[i].operands, out[i].text))
    else:                                            # right objects, wrong order
        j = (i + 1) % len(out)
        out[i], out[j] = out[j], out[i]
    return out


def is_loser(actions: Sequence[Action], goal: Goal) -> bool:
    editor = SceneEditor(resolution=8)
    editor.reset()
    editor.run(list(actions))
    return not goal.satisfied(editor.state)


def build_pair(item: Item, rng: np.random.Generator, tries: int = 8):
    """(winner, loser) action sequences, both checked by the environment."""
    winner = list(item.truth["actions"])
    goal: Goal = item.truth["goal"]
    for _ in range(tries):
        candidate = corrupt(winner, rng)
        if is_loser(candidate, goal):
            return winner, candidate
    return None


def action_batch(item: Item, actions: Sequence[Action], dims: dict[str, int],
                 device=None) -> TensorBatch:
    spans = [s for s in item.sample.spans if not s.supervised]
    spans = spans + [
        control_span(3),
        Span("action", actions_to_span_payload(list(actions)), supervised=True,
             atomic=False),
        control_span(2),
    ]
    return TensorBatch(collate([Sample(spans)], dims), device=device)


def action_logprob(model, batch: TensorBatch, n_loops: int = 1) -> torch.Tensor:
    out = model(batch, n_loops=n_loops)
    h = out.hidden[:, :-1]
    target = batch.discrete[:, 1:]
    mask = (
        batch.supervised[:, 1:]
        & batch.valid[:, 1:]
        & (batch.modality[:, 1:] == MODALITY_INDEX["action"])
    )
    op_logits, scalars = model.codecs.action_head(h)
    logp = -F.cross_entropy(
        op_logits.reshape(-1, op_logits.shape[-1]),
        target.reshape(-1).clamp(0, op_logits.shape[-1] - 1),
        reduction="none",
    ).view_as(mask)
    # Operands are continuous: a Gaussian log-density with unit scale keeps the
    # two halves of an action on one comparable scale.
    operand_ll = -0.5 * (scalars - batch.scalars[:, 1:]).pow(2).sum(-1)
    return ((logp + operand_ll) * mask).sum()


def dpo_step(model, reference, item, rng, dims, beta: float = 0.1
             ) -> Optional[torch.Tensor]:
    pair = build_pair(item, rng)
    if pair is None:
        return None
    winner, loser = pair
    device = device_of(model)
    bw = action_batch(item, winner, dims, device=device)
    bl = action_batch(item, loser, dims, device=device)
    lw = action_logprob(model, bw)
    ll = action_logprob(model, bl)
    with torch.no_grad():
        rw = action_logprob(reference, bw)
        rl = action_logprob(reference, bl)
    margin = beta * ((lw - rw) - (ll - rl))
    return -F.logsigmoid(margin)


def train_dpo(
    model, items: Sequence[Item], steps: int = 100, lr: float = 5e-5,
    beta: float = 0.1, seed: int = 0, log_every: int = 20,
) -> list[dict]:
    dims = continuous_dims(model.cfg.codecs)
    reference = copy.deepcopy(model).eval()
    for p in reference.parameters():
        p.requires_grad_(False)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    rng = np.random.default_rng(seed)
    history = []
    for step in range(steps):
        item = items[int(rng.integers(len(items)))]
        model.train()
        loss = dpo_step(model, reference, item, rng, dims, beta)
        if loss is None:
            continue
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        optimizer.zero_grad(set_to_none=True)
        record = {"step": step, "dpo_loss": float(loss.detach())}
        history.append(record)
        if step % log_every == 0:
            print(f"dpo step {step:4d}  loss={record['dpo_loss']:.4f}", flush=True)
    return history


@torch.no_grad()
def goal_success_rate(model, items: Sequence[Item], n_loops: int = 1) -> dict[str, float]:
    """Execute the model's own first action and ask the environment."""
    from ..evaluation.harness import _grade_scene

    result = _grade_scene(model, list(items), n_loops)
    return {
        "goal_success": result.accuracy,
        "first_opcode_accuracy": result.extra.get("first_opcode_accuracy", 0.0),
        "n": float(result.n),
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--init", required=True)
    ap.add_argument("--steps", type=int, default=150)
    ap.add_argument("--lr", type=float, default=5e-5)
    ap.add_argument("--beta", type=float, default=0.1)
    ap.add_argument("--items", type=int, default=400)
    ap.add_argument("--threads", type=int, default=4)
    ap.add_argument("--out", default="runs/phase4")
    args = ap.parse_args(argv)

    torch.set_num_threads(args.threads)
    from .datasets import build_corpus

    model, manifest = load_checkpoint(args.init)
    corpus = build_corpus(args.items, seed=21, split="train")
    items = [it for it in corpus.items if it.family == "scene_goal"]
    test = [it for it in build_corpus(200, seed=22, split="test").items
            if it.family == "scene_goal"]
    print(f"{len(items)} training scenes, {len(test)} test scenes")

    before = goal_success_rate(model, test)
    history = train_dpo(model, items, steps=args.steps, lr=args.lr, beta=args.beta)
    after = goal_success_rate(model, test)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {"before": before, "after": after, "history": history}
    (out_dir / "phase4.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    torch.save({"state_dict": model.state_dict(), "manifest": manifest},
               out_dir / "phase4-final.pt")
    print(json.dumps({"before": before, "after": after}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
