"""Multi-turn conversation: the format, and a session that holds one.

**One definition, used by both sides.** The role markers and the turn layout
below are what the training data is built from *and* what generation conditions
on. A chat format that differs between training and inference by a single token
produces a model that answers fluently in training and emits noise in the chat
box, with nothing in the loss curve to indicate why — so
``data/chat_corpus.py`` imports this module rather than restating the layout.

The layout::

    BOS  USER "how deep is the channel"  ASSISTANT "about 1.5 m"  EOS
         USER "and if I double it"       ASSISTANT "…"            EOS

Only the assistant's bytes are supervised. The user's turns are context the
model must condition on and must never be scored for predicting — training on
them teaches the model to write the human's next message, which is the single
most common way a small chat model ends up interviewing itself.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Sequence

from ..codecs.spans import Sample, Span, text_span

#: Role markers, in the control-token block reserved below ``TEXT_OFFSET``.
#: 1–6 are taken (BOS, EOS, SEP, PAD, VERDICT_TRUE, VERDICT_FALSE). 10 was
#: already spent, before this module had any tool-use story, by
#: ``iridium.agency.media_agent``: a self-contained media-editing agent loop
#: that stuffs both its state-refresh turns *and* its tool results under one
#: generic ``ROLE_TOKEN['tool']``, with the call itself just JSON text inside
#: an ordinary ASSISTANT turn. That module is out of this file's ownership
#: and is left exactly as it is — id 10 stays assigned to ``"tool"`` and
#: unused by everything below.
#:
#: ``TOOL_CALL``/``TOOL_RESULT`` are new, and deliberately two *different*
#: ids rather than a reuse of ``"tool"``: supervision differs by direction
#: (a call is the model's own output and is trained on; a result is
#: environment output and never is — see ``conversation_spans``), and a
#: single shared marker cannot let a loss mask tell those apart from the
#: control token alone. They are reserved ids, not the text tags
#: (``<tool_call>``literally what ``NousResearch/hermes-function-calling-v1``
#: and ``glaiveai/glaive-function-calling-v2`` use, and what
#: ``iridium.agency.media_agent`` also falls back on for the call itself) a
#: production tool-calling format would use instead: a byte-level tokenizer
#: can split a text tag across an arbitrary number of tokens depending on
#: what precedes it, a user could type the literal string in a chat message
#: and be misread as issuing a call, and every occurrence costs real sequence
#: budget. A reserved control id below ``TEXT_OFFSET`` is atomic, cannot
#: appear in user text (bytes only start at ``TEXT_OFFSET``), and costs
#: exactly one token no matter what precedes it.
USER, ASSISTANT, SYSTEM = 7, 8, 9
TOOL_CALL, TOOL_RESULT = 11, 12
ROLE_TOKEN = {
    "user": USER, "assistant": ASSISTANT, "system": SYSTEM, "tool": 10,
    "tool_call": TOOL_CALL, "tool_result": TOOL_RESULT,
}
TOKEN_ROLE = {v: k for k, v in ROLE_TOKEN.items()}

BOS, EOS = 1, 2
TEXT_OFFSET = 16

#: Generation stops on either: the assistant ending its turn, or the assistant
#: starting a *user* turn — a small model does the latter constantly, and
#: without this the transcript fills with invented dialogue. A tool call also
#: ends its own turn on EOS (see ``conversation_spans``), so this set does not
#: need ``TOOL_CALL`` itself; it would only need to appear here if the model
#: could emit it as a bare turn-opener the way it can emit USER/SYSTEM, and it
#: cannot — a tool call is content *inside* an assistant turn, not a role a
#: turn can open with.
STOP_IDS = (EOS, USER, SYSTEM)


@dataclass
class Turn:
    role: str
    text: str

    def __post_init__(self) -> None:
        if self.role not in ROLE_TOKEN:
            raise ValueError(f"unknown role {self.role!r}; known: {sorted(ROLE_TOKEN)}")


def _control(code: int, supervised: bool = False) -> Span:
    import numpy as np
    return Span("control", np.array([code], dtype=np.int64), supervised=supervised)


#: Turns generated by the model itself, i.e. eligible for supervision. A tool
#: call is exactly as much "the assistant's own output" as a prose reply is —
#: it is what the model chose to emit, and training on it is what teaches the
#: model to call tools in the first place.
_MODEL_TURNS = ("assistant", "tool_call")


def conversation_spans(
    turns: Sequence[Turn],
    supervise_assistant: bool = True,
    open_for_reply: bool = False,
) -> list[Span]:
    """The exact span layout, for training and for inference alike.

    ``open_for_reply`` appends a trailing ASSISTANT marker and nothing after
    it, which is how generation is asked for a reply: the model is positioned
    exactly where its own bytes begin during training.

    A ``"tool_result"`` turn is **never** supervised, regardless of
    ``supervise_assistant`` — it is the environment's own output (whatever
    ``ToolRegistry.call`` returned), not something the model produced, and the
    one thing worse than a model that cannot call tools is one trained to
    *predict* what a tool will say and never actually call it. This mirrors
    exactly why user turns are never supervised in this same function, one
    paragraph up in the module docstring, for the mirror-image reason: there
    it is "don't teach the model to write the other party's lines", here it is
    "don't teach the model to hallucinate the world's response instead of
    querying it."
    """
    spans: list[Span] = [_control(BOS)]
    for turn in turns:
        spans.append(_control(ROLE_TOKEN[turn.role]))
        supervised = supervise_assistant and turn.role in _MODEL_TURNS
        if turn.text:
            spans.append(text_span(turn.text, supervised=supervised,
                                   offset=TEXT_OFFSET))
        if turn.role in _MODEL_TURNS:
            spans.append(_control(EOS, supervised=supervised))
    if open_for_reply:
        spans.append(_control(ASSISTANT))
    return spans


def conversation_sample(
    turns: Sequence[Turn],
    supervise_assistant: bool = True,
    open_for_reply: bool = False,
    meta: Optional[dict] = None,
) -> Sample:
    return Sample(
        conversation_spans(turns, supervise_assistant, open_for_reply),
        meta=meta or {"family": "chat"},
    )


def fit_to_budget(turns: Sequence[Turn], max_bytes: int) -> list[Turn]:
    """Drop whole turns from the front until the history fits.

    Whole turns, not truncated bytes: a half-sentence of someone else's message
    is worse context than no message, and cutting mid-turn leaves a role marker
    describing text that is no longer there.
    """
    kept: list[Turn] = []
    total = 0
    for turn in reversed(turns):
        cost = len(turn.text.encode("utf-8")) + 2
        if total + cost > max_bytes and kept:
            break
        kept.append(turn)
        total += cost
    return list(reversed(kept))


@dataclass
class ChatSession:
    """A conversation with one model, held across turns.

    Sampling defaults are chosen for a *small* model. Greedy decoding on an
    undertrained network loops within a sentence or two; temperature alone
    makes it incoherent. Nucleus sampling with a repetition penalty is what
    keeps a model this size producing something readable, and it is still the
    training that decides whether the text means anything.
    """

    model: object
    system: Optional[str] = None
    temperature: float = 0.8
    top_p: float = 0.92
    top_k: int = 0
    repetition_penalty: float = 1.15
    max_new_tokens: int = 160
    n_loops: Optional[int] = None
    seed: int = 0
    turns: list[Turn] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.system:
            self.turns.insert(0, Turn("system", self.system))

    # -- history -----------------------------------------------------------

    def reset(self) -> None:
        self.turns = [Turn("system", self.system)] if self.system else []

    def history(self) -> list[tuple[str, str]]:
        return [(t.role, t.text) for t in self.turns]

    def _budget(self, max_new_tokens: Optional[int] = None) -> int:
        cfg = self.model.cfg
        # Leave room for the reply, BOS and the open ASSISTANT marker. The
        # per-turn cost in fit_to_budget includes the remaining role markers.
        reply_tokens = self.max_new_tokens if max_new_tokens is None else max_new_tokens
        return cfg.max_seq_len - reply_tokens - 2

    # -- the actual exchange ----------------------------------------------

    def send(self, message: str, **overrides) -> str:
        """Append a user message, generate a reply, append and return it."""
        from .generate import generate

        params = dict(
            max_new_tokens=self.max_new_tokens,
            temperature=self.temperature,
            top_p=self.top_p,
            top_k=self.top_k,
            repetition_penalty=self.repetition_penalty,
            stop_ids=STOP_IDS,
            n_loops=self.n_loops,
            seed=self.seed,
            text_offset=TEXT_OFFSET,
            text_only=True,
        )
        params.update(overrides)

        max_new_tokens = params["max_new_tokens"]
        if not isinstance(max_new_tokens, int) or max_new_tokens < 1:
            raise ValueError("max_new_tokens must be a positive integer")
        max_seq_len = self.model.cfg.max_seq_len
        message_bytes = len(message.encode("utf-8"))
        if message_bytes + max_new_tokens + 3 > max_seq_len:
            raise ValueError(
                f"message is {message_bytes} UTF-8 bytes; at most "
                f"{max(0, max_seq_len - max_new_tokens - 3)} fit with the "
                f"requested {max_new_tokens}-token reply budget"
            )

        # A failed generation or an oversize message must not corrupt history.
        candidate = [*self.turns, Turn("user", message)]
        context = fit_to_budget(candidate, self._budget(max_new_tokens))
        # Budgeting can discard a user turn but retain its following assistant
        # turn. Do not prompt the model with an orphaned assistant response.
        while context and context[0].role == "assistant":
            context = context[1:]
        sample = conversation_sample(context, supervise_assistant=False,
                                     open_for_reply=True)
        if len(sample) + max_new_tokens > max_seq_len:
            raise ValueError("conversation exceeds the model context window")
        reply = generate(self.model, sample, **params).text.strip()
        self.seed += 1  # Change sampling even if the model ends a turn blank.

        if not reply:
            # An untrained or barely-trained model ends its turn immediately.
            # Printing a blank line looks like a bug in the notebook; saying so
            # points at the actual cause, which is the training, not the chat.
            reply = ("(no output — the model ended its turn immediately. That is "
                     "what an undertrained model does; train for more steps, or "
                     "raise CHAT_WEIGHT so more of the corpus is conversation.)")
            return reply

        self.turns = [*candidate, Turn("assistant", reply)]
        return reply

    def transcript(self) -> str:
        lines = []
        for turn in self.turns:
            if turn.role == "system":
                continue
            who = "you" if turn.role == "user" else "iridium"
            lines.append(f"{who}: {turn.text}")
        return "\n".join(lines)
