"""Conversations to train on, with their licences recorded.

A model only chats if something taught it the shape of a conversation. Byte
prediction over books and encyclopedia articles produces a model that continues
prose, which is a different skill: prompted with "what is a weir?" it writes the
*next paragraph of an article about weirs* rather than answering. The turn-taking
has to be in the data.

Two human-written, permissively licensed corpora:

* **Dolly 15k** (CC BY-SA 3.0) — single-turn instruction/response written by
  people, some with a supplied context passage.
* **OASST1** (Apache 2.0) — real multi-turn assistant conversations, released
  as a message *forest*: rows carry ``parent_id``, and a conversation is a root
  and one chain of replies. Reconstructed here rather than flattened, because
  multi-turn context is the part single-turn data cannot teach.

What this does not do is make the model's answers true. These corpora teach the
*form* of a reply. Everything this project says about grading — that a number
means nothing without the baseline beside it — applies with more force here,
because fluent conversational text is the most convincing possible disguise for
a model that knows nothing.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Iterator, Optional

import numpy as np

from ..runtime.chat import Turn


@dataclass(frozen=True)
class ChatSourceSpec:
    key: str
    dataset: str
    config: Optional[str]
    split: str
    licence: str
    obligation: str
    description: str
    homepage: str = ""
    approx_rows: int = 10_000
    #: Whether the licence *as stated on the dataset card* permits commercial
    #: use. False also covers "unclear" -- e.g. data generated by a model whose
    #: provider's terms restrict training competing models on its outputs.
    commercial_ok: bool = True
    #: Who wrote the replies: "human", or the model family that generated them.
    #: Distilled data teaches that model's habits and mistakes too.
    written_by: str = "human"
    #: Opt-in sources are registered and loadable, but never in a default mix.
    opt_in: bool = False
    #: Columns to read; ``None`` reads all. Streaming parquet materialises
    #: whole row groups, so skipping a wide unused column (OpenR1's traces)
    #: is the difference between ~1 GB and ~4 GB of host RAM.
    columns: Optional[tuple[str, ...]] = None

    def as_dict(self) -> dict:
        return asdict(self)


CHAT_SOURCES: dict[str, ChatSourceSpec] = {
    "dolly": ChatSourceSpec(
        key="dolly",
        dataset="databricks/databricks-dolly-15k",
        config=None,
        split="train",
        licence="CC BY-SA 3.0",
        obligation=(
            "Attribution to Databricks and share-alike on derivative datasets. "
            "Recorded in the run manifest for exactly that reason."
        ),
        description=(
            "15k instruction/response pairs written by Databricks employees. "
            "Human-written throughout, which is why it is here: a corpus of one "
            "model's outputs would teach this model to imitate that model's "
            "mistakes, with no way to tell which are which."
        ),
        homepage="https://huggingface.co/datasets/databricks/databricks-dolly-15k",
        approx_rows=15_000,
    ),
    "oasst": ChatSourceSpec(
        key="oasst",
        dataset="OpenAssistant/oasst1",
        config=None,
        split="train",
        licence="Apache 2.0",
        obligation="Retain the licence and attribution notices.",
        description=(
            "Crowd-sourced multi-turn assistant conversations, human written and "
            "human ranked. Filtered here to English, undeleted, review-passed "
            "messages, keeping the highest-ranked reply at each step."
        ),
        homepage="https://huggingface.co/datasets/OpenAssistant/oasst1",
        approx_rows=84_400,
    ),
    # Licences below were read from each dataset card (2026-09). A card's
    # licence covers the dataset; it does not settle the terms of the model
    # that generated synthetic replies, which is what ``commercial_ok`` and
    # ``written_by`` are for.
    "smol_smoltalk": ChatSourceSpec(
        key="smol_smoltalk",
        dataset="HuggingFaceTB/smol-smoltalk",
        config=None,
        split="train",
        licence="Apache 2.0",
        obligation="Retain the licence and attribution notices.",
        description=(
            "The SmolTalk subset Hugging Face built for models under 1B "
            "parameters (SmolLM2-135M/360M-Instruct): shorter conversations, "
            "less task-specific data. The closest published match to what a "
            "34-100M model can absorb."
        ),
        homepage="https://huggingface.co/datasets/HuggingFaceTB/smol-smoltalk",
        approx_rows=460_000,
        written_by=("synthetic, largely open-weight Llama 3.1 outputs (Magpie-Ultra); "
                    "the Llama licence adds naming conditions to distributed models "
                    "trained on them -- check the card before any release"),
    ),
    "openr1_math": ChatSourceSpec(
        key="openr1_math",
        dataset="open-r1/OpenR1-Math-220k",
        config="default",
        split="train",
        licence="Apache 2.0",
        obligation="Retain the licence and attribution notices.",
        description=(
            "Competition-style maths problems with worked solutions. Only the "
            "`solution` field is used, not the multi-thousand-token R1 traces: "
            "a small model with a 1-2k window cannot hold a trace, and training "
            "on truncated reasoning teaches it to stop mid-thought."
        ),
        homepage="https://huggingface.co/datasets/open-r1/OpenR1-Math-220k",
        approx_rows=93_700,
        written_by="human-written solutions (NuminaMath)",
        columns=("problem", "solution"),
    ),
    "ultrachat": ChatSourceSpec(
        key="ultrachat",
        dataset="HuggingFaceH4/ultrachat_200k",
        config=None,
        split="train_sft",
        licence="MIT",
        obligation="Retain the licence notice.",
        description=(
            "Filtered multi-turn dialogues (the Zephyr SFT set). The dataset is "
            "MIT, but the dialogues were generated by ChatGPT, whose provider "
            "terms restrict using outputs to build competing models; opt-in "
            "for that reason."
        ),
        homepage="https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k",
        approx_rows=207_900,
        commercial_ok=False,
        written_by="ChatGPT",
        opt_in=True,
    ),
    "tulu3": ChatSourceSpec(
        key="tulu3",
        dataset="allenai/tulu-3-sft-mixture",
        config=None,
        split="train",
        licence="ODC-By 1.0 overall; some subsets non-commercial (see card)",
        obligation="Attribution; per-subset terms, some non-commercial.",
        description=(
            "The Tulu 3 SFT mixture: broad instruction following, maths, code, "
            "safety. Presented by its authors as a research artifact with "
            "non-commercial portions, so opt-in."
        ),
        homepage="https://huggingface.co/datasets/allenai/tulu-3-sft-mixture",
        approx_rows=939_000,
        commercial_ok=False,
        written_by="mixed human and synthetic",
        opt_in=True,
    ),
}

#: Default: commercially usable sources only. Small-model-sized synthetic chat
#: carries most of the weight; the human-written sets keep it honest; worked
#: maths solutions supply the reasoning share.
DEFAULT_CHAT_MIX = {"smol_smoltalk": 0.45, "oasst": 0.20, "dolly": 0.15, "openr1_math": 0.20}

#: Everything registered, opt-in sources included. Private use only unless every
#: source's terms have been checked for the intended use.
MAX_CHAT_MIX = {"smol_smoltalk": 0.30, "ultrachat": 0.20, "tulu3": 0.20, "oasst": 0.10,
                "dolly": 0.05, "openr1_math": 0.15}


def chat_licence_notice(keys=None) -> str:
    lines = ["Conversation corpora and their terms:", ""]
    for key in (keys or DEFAULT_CHAT_MIX):
        spec = CHAT_SOURCES[key]
        lines += [
            f"* {spec.dataset}",
            f"    licence:     {spec.licence}",
            f"    obligation:  {spec.obligation}",
            f"    homepage:    {spec.homepage}",
        ]
    lines += [
        "",
        "These teach the form of a reply, not the truth of one. A fluent answer",
        "from a model this size is still an unverified answer.",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------


def _load(spec: ChatSourceSpec, streaming: bool = True):
    try:
        from datasets import load_dataset
    except ImportError as exc:                          # pragma: no cover
        raise RuntimeError(
            "pip install datasets  — required for conversational training"
        ) from exc
    extra = {"columns": list(spec.columns)} if spec.columns else {}
    return load_dataset(spec.dataset, spec.config, split=spec.split,
                        streaming=streaming, **extra)


def dolly_conversations(limit: Optional[int] = None, seed: int = 0
                        ) -> Iterator[list[Turn]]:
    """Instruction (+ optional context) -> response, as a two-turn exchange."""
    spec = CHAT_SOURCES["dolly"]
    ds = _load(spec).shuffle(seed=seed, buffer_size=1000)
    produced = 0
    for row in ds:
        instruction = (row.get("instruction") or "").strip()
        context = (row.get("context") or "").strip()
        response = (row.get("response") or "").strip()
        if not instruction or not response:
            continue
        prompt = f"{instruction}\n\n{context}" if context else instruction
        yield [Turn("user", prompt), Turn("assistant", response)]
        produced += 1
        if limit is not None and produced >= limit:
            return


def oasst_conversations(limit: Optional[int] = None, seed: int = 0,
                        lang: str = "en", max_turns: int = 6,
                        ) -> Iterator[list[Turn]]:
    """Rebuild conversation threads from the message forest.

    The rows are a forest, not a list: each carries ``parent_id``, and a usable
    conversation is a root plus one chain of replies. Treating the rows as
    independent examples — which the flat schema invites — trains the model on
    replies whose questions it never saw.

    The whole split is materialised (about 40 MB of parquet) because a thread
    cannot be assembled from a stream that has not yet reached its children.
    """
    spec = CHAT_SOURCES["oasst"]
    rows = [
        r for r in _load(spec, streaming=False)
        if r.get("lang") == lang and not r.get("deleted")
        and (r.get("text") or "").strip()
    ]
    by_parent: dict[Optional[str], list[dict]] = {}
    for row in rows:
        by_parent.setdefault(row.get("parent_id"), []).append(row)

    def best(children: list[dict]) -> dict:
        # rank 0 is the top-ranked reply; unranked sorts last.
        return min(children, key=lambda r: (r.get("rank") is None, r.get("rank") or 0))

    roots = [r for r in rows if not r.get("parent_id") and r.get("role") == "prompter"]
    rng = np.random.default_rng(seed)
    rng.shuffle(roots)

    produced = 0
    for root in roots:
        turns: list[Turn] = []
        node = root
        while node is not None and len(turns) < max_turns:
            role = "user" if node.get("role") == "prompter" else "assistant"
            turns.append(Turn(role, (node["text"] or "").strip()))
            children = by_parent.get(node["message_id"])
            node = best(children) if children else None
        # A thread that ends on the user is an unanswered question: there is
        # nothing for the model to learn to say.
        while turns and turns[-1].role != "assistant":
            turns.pop()
        if len(turns) < 2:
            continue
        yield turns
        produced += 1
        if limit is not None and produced >= limit:
            return


_ROLES = {"user": "user", "human": "user", "assistant": "assistant", "gpt": "assistant",
          "system": "system"}


def _messages_loader(key: str):
    """Loader for any source in the common ``messages: [{role, content}]`` layout."""

    def load(limit: Optional[int] = None, seed: int = 0, max_turns: int = 8
             ) -> Iterator[list[Turn]]:
        spec = CHAT_SOURCES[key]
        ds = _load(spec).shuffle(seed=seed, buffer_size=1000)
        produced = 0
        for row in ds:
            turns = []
            for message in row.get("messages") or []:
                role = _ROLES.get((message.get("role") or "").lower())
                text = (message.get("content") or "").strip()
                if role is None or not text:
                    turns = []                # unknown role (e.g. tool): skip the row
                    break
                turns.append(Turn(role, text))
            turns = turns[:max_turns]
            while turns and turns[-1].role != "assistant":
                turns.pop()
            if sum(t.role == "assistant" for t in turns) < 1:
                continue
            yield turns
            produced += 1
            if limit is not None and produced >= limit:
                return

    load.__name__ = f"{key}_conversations"
    return load


def openr1_math_conversations(limit: Optional[int] = None, seed: int = 0
                              ) -> Iterator[list[Turn]]:
    """Problem -> worked solution. See the source spec for why not the traces."""
    spec = CHAT_SOURCES["openr1_math"]
    ds = _load(spec).shuffle(seed=seed, buffer_size=1000)
    produced = 0
    for row in ds:
        problem = (row.get("problem") or "").strip()
        solution = (row.get("solution") or "").strip()
        if not problem or not solution:
            continue
        yield [Turn("user", problem), Turn("assistant", solution)]
        produced += 1
        if limit is not None and produced >= limit:
            return


CONVERSATION_LOADERS = {
    "dolly": dolly_conversations,
    "oasst": oasst_conversations,
    "smol_smoltalk": _messages_loader("smol_smoltalk"),
    "ultrachat": _messages_loader("ultrachat"),
    "tulu3": _messages_loader("tulu3"),
    "openr1_math": openr1_math_conversations,
}


# --------------------------------------------------------------------------
# training items
# --------------------------------------------------------------------------


def chat_items(
    n_items: int,
    mix: Optional[dict[str, float]] = None,
    seed: int = 0,
    max_bytes: int = 1024,
    split: str = "train",
    tokenizer=None,
    max_tokens: Optional[int] = None,
):
    """Conversations as training items, supervised on the assistant only.

    A source can underfill: conversations whose single reply is longer than
    ``max_bytes`` cannot be fitted and are skipped, and some sources are mostly
    long answers. Rather than failing a whole training run over it, the
    shortfall is topped up from the other sources in the mix, and the run
    fails only if the mix as a whole cannot supply ``n_items``.
    """
    from ..training.datasets import allocate_mixture
    from .text_corpus import SPLIT_SHARES

    mix = mix or DEFAULT_CHAT_MIX
    quotas = allocate_mixture(n_items, mix)
    lo, hi = SPLIT_SHARES.get(split, SPLIT_SHARES["train"])
    seen: set[int] = set()
    items: list = []
    shortfall = 0
    exhausted: set[str] = set()
    for i, (key, quota) in enumerate(sorted(quotas.items())):
        if quota <= 0:
            continue
        got = _take(key, quota, seed + i, split, max_bytes, lo, hi, seen, items, tokenizer, max_tokens)
        if got < quota:
            shortfall += quota - got
            exhausted.add(key)
    # Top up from the sources that did not run dry, fresh seeds so the scan
    # reaches rows the first pass did not; ``seen`` keeps it from repeating.
    spare = [k for k in sorted(quotas) if quotas[k] > 0 and k not in exhausted]
    round_ = 1
    while shortfall and spare and round_ <= 4:
        for j, key in enumerate(list(spare)):
            share = -(-shortfall // max(len(spare) - j, 1))
            got = _take(key, share, seed + 1000 * round_ + j, split, max_bytes, lo, hi,
                        seen, items, tokenizer, max_tokens)
            shortfall -= got
            if got < share:
                spare.remove(key)
            if not shortfall:
                break
        round_ += 1

    rng = np.random.default_rng(seed)
    rng.shuffle(items)
    return items[:n_items]


def _take(key, quota, seed, split, max_bytes, lo, hi, seen, items, tokenizer,
          max_tokens=None) -> int:
    """Append up to ``quota`` fitted conversations from ``key``; return how many."""
    from ..runtime.chat import conversation_sample, fit_to_budget
    from ..training.tasks import Item
    from .text_corpus import in_split

    got = 0
    # Scan generously: held-out splits keep ~10% of rows, and long replies are
    # skipped, so a small multiple of the quota routinely underfills.
    budget = int(np.ceil(8 * quota * 100 / (hi - lo))) + 64
    for turns in CONVERSATION_LOADERS[key](limit=budget, seed=seed):
        joined = "\n".join(t.text for t in turns)
        if not in_split(joined, split):
            continue
        fingerprint = hash(joined)
        if fingerprint in seen:
            continue
        turns = fit_to_budget(turns, max_bytes)
        # A system prompt may lead; an assistant turn may not.
        while turns and turns[0].role == "assistant":
            turns = turns[1:]
        users = [t for t in turns if t.role == "user"]
        if not users or turns[-1].role != "assistant":
            continue
        kwargs = {"tokenizer": tokenizer} if tokenizer is not None else {}
        sample = conversation_sample(turns, supervise_assistant=True,
                                     meta={"family": "chat", "source": key}, **kwargs)
        # Bytes only bound tokens loosely; a reply cut off by the window has
        # no targets left and would stop training, so it is skipped here.
        if max_tokens is not None and len(sample) > max_tokens:
            continue
        seen.add(fingerprint)
        items.append(Item(
            sample=sample,
            family="chat",
            prompt=users[-1].text[:80],
            answer=turns[-1].text,
            truth={"source": key, "turns": len(turns)},
        ))
        got += 1
        if got >= quota:
            break
    return got
